name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write 

    steps:
    - uses: actions/checkout@v3
    - name: Fetch FTC SDK
      run: git clone https://github.com/FIRST-Tech-Challenge/FtcRobotController FtcRobotControllerTemplate
    - name: Contextualize code
      continue-on-error: true
      run: mv ./* FtcRobotControllerTemplate/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/
    - name: Move FTC SDK
      continue-on-error: true
      run: mv FtcRobotControllerTemplate/* .
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Pre-build debug find
      run: find .
    - name: Build with Gradle
      run: ./gradlew build
    # https://dev.to/doctolib/github-actions-how-to-push-a-github-status-in-addition-of-github-checks-3d27
    - name: "Create a check run"
      uses: actions/github-script@v6
      env:
        parameter_url: '${{ github.event.workflow_run.html_url }}'
      with:
        debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}
        script: |
          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head_sha: context.sha,
            name: "android-build",
            status: "completed",
            // Careful, code injection can happen.
            conclusion: "${{ github.event.workflow_run.conclusion }}",
            // This is safe, not string interpolation.
            details_url: process.env.parameter_url,
            output: {
              title: "Android Build",
              summary: "Automated android build",
              text: "This may take a bit of time. Only bypass (if you can) if you are 100% sure you are in the right and you are in a hurry.",
            },
          });
