name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fetch submodules
      run: bash ./scripts/submodule.sh
    - name: Fetch FTC SDK
      run: git clone https://github.com/FIRST-Tech-Challenge/FtcRobotController
    - name: Contextualize code
      run: mv *.java FtcRobotController/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/
    - name: Move FTC SDK
      run: mv FtcRobotController/* .
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
